name: XemChatProtection
version: '${project.version}'
main: me.xemu.xemchatprotection.XemChatProtection
authors: [ Xemu ]
description: XemChatProtection is back, and stronger than ever.

commands:
  cp:
    description: XemChatProtection's main command
    aliases: [chatprotection, xcp, xemuchatprotection]